### ISSUE TITLE
[BUG] cupyx.scipy.ndimage.gaussian_laplace odd behavior

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [rapidsai/cucim#269] opened 2022-04-22 14:54 UTC
**Describe the bug**
The gaussian laplace filter behaves as anticipated for filter sizes <10.  However, once the filter size >= 10, there seems to be no filter response.  It does not throw an error though.

**Steps/Code to reproduce bug**
Currently using a simple workflow:
```
from cupyx.scipy.ndimage import gaussian_laplace as LoG
import os
from tifffile import imread, imwrite
import cupy as cp

def plot_projections_from_gpu(gpu_data):
    titles = ['XY', 'XZ', 'YZ']
    fig, axs = plt.subplots(nrows=1, 
                            ncols=3, 
                            figsize=(10, 3))

    for i in range(3):
        gpu_max = cp.max(gpu_data, axis=i)        
        axs[i].imshow(gpu_max.get())
        axs[i].axis('off')
        axs[i].set_title(titles[i])
    plt.show()

data_directory = '/archive/MIL/dean/2022-04-21-metastasis-detection'
image_name = 'test_007.tif'
image_data = imread(os.path.join(data_directory, image_name))
image_gpu = cp.asarray(image_data, dtype=np.uint32)
image_gpu = LoG(image_gpu, sigma=(9,9,9)) 
plot_projections_from_gpu(image_gpu)
```

Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
The filter should provide a response at sigma values > 9. 

**Environment details (please complete the following information):**
Anaconda environment.  Linux.  Environment appears fully functional.

**Additional context**

**Comment by gigony** [comment] 2022-05-04 07:59
@AdvancedImagingUTSW Thanks for filing the issue!

cuCIM is providing scikit-image API using CuPy and I would like to note that the example you showed seems to be more related to [CuPy](https://github.com/cupy/cupy) project, not cuCIM because gaussian_laplace is CuPy's built-in method (`cupyx.scipy.ndimage`).

@grlee77 I tried to execute it with arbitrary RGB image.

```bash
python3 -m pip install matplotlib tifffile numpy cupy-cuda111
wget https://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-Small-Region.svs
```

**test_laplace.py**

```python
from cupyx.scipy.ndimage import gaussian_laplace as LoG
import os
from matplotlib import pyplot as plt
from tifffile import imread, imwrite
import numpy as np
import cupy as cp


def plot_projections_from_gpu(gpu_data):
    titles = ['XY', 'XZ', 'YZ']
    fig, axs = plt.subplots(nrows=1,
                            ncols=3,
                            figsize=(10, 3))

    for i in range(3):
        gpu_max = cp.max(gpu_data, axis=i)
        axs[i].imshow(gpu_max.get())
        axs[i].axis('off')
        axs[i].set_title(titles[i])
    plt.show()

data_directory = '.'
image_name = 'CMU-1-Small-Region.svs'
image_data = imread(os.path.join(data_directory, image_name))
print(image_data.shape)
image_gpu = cp.asarray(image_data, dtype=np.uint32)
image_gpu = LoG(image_gpu, sigma=(9, 9, 9))
plot_projections_from_gpu(image_gpu)
```

```bash
python test_laplace.py
```

**sigma=(2,2,2)**
![image](https://user-images.githubusercontent.com/1928522/166640433-8ca93e5d-e556-4aca-81f5-56b4b510d581.png)
**sigma=(6,6,6)**
![image](https://user-images.githubusercontent.com/1928522/166641464-a8c80052-bf11-4a68-be6a-b0749750b1bf.png)
**sigma=(9,9,9)**
![image](https://user-images.githubusercontent.com/1928522/166640493-7fdb90c0-40d4-4199-9609-d425cc2cfcfb.png)
**sigma=(11,11,11)**
![image](https://user-images.githubusercontent.com/1928522/166640553-e2713a86-ef22-4520-99b4-5997dc95b005.png)

I don't know the algorithm(https://docs.cupy.dev/en/stable/reference/generated/cupyx.scipy.ndimage.gaussian_laplace.html) and required types (does it support uint32 type?) in detail but it is possible that the problem comes from the use of `np.uint32` type.

If I change the following line with `float32` (instead of `uint32`)
```python
#image_gpu = cp.asarray(image_data, dtype=np.uint32)
image_gpu = cp.asarray(image_data, dtype=cp.float32)
```
It seems to work well.
**sigma=(5,5,5)**
![image](https://user-images.githubusercontent.com/1928522/166642700-0c8549e0-635a-464f-99c2-3c8e918aaab9.png)

**sigma=(11,11,11)**
![image](https://user-images.githubusercontent.com/1928522/166642648-29fe34c3-bd5f-4c37-a734-5fc3af191157.png)

What do you think?

**Comment by grlee77** [comment] 2022-05-04 13:24
Thanks for looking into this @gigony. Indeed for `cupyx.scipy.ndimage` the default is to create an output array with the same dtype as the input. You would not necessarily have to explicitly convert the input array to get the floating point output though. You can instead specify, `output=cp.float32` to specify that the output should be in floating point. 

```Python
image_gpu = LoG(image_gpu, sigma=(9, 9, 9), output=cp.float32)
```

or equivalently, you could preallocate an output array (when specifying just the dtype as above, LoG would do those for you internally)
```Python
output = cp.empty(image_gpu.shape, dtype=cp.float32)
image_gpu = LoG(image_gpu, sigma=(9, 9, 9), output=output)
```

Note that, in general the input and output arrays should NOT be the same array as most ndimage functions don't support in-place filtering. IIRC, we added checks in SciPy and CuPy that will raise an error if the input and output arrays overlap in memory.


Aside from the identified dtype issue, there is another, more subtle numerical error in SciPy's (and CuPy's) `gaussian_filter` when order > 0 (the `gaussian_laplace` function discussed in this PR calls `gaussian_filter` with `order=2` under the hood). There is some discussion of corrections for this in https://dsp.stackexchange.com/questions/78280/are-scipy-second-order-gaussian-derivatives-correct. It may be worth implementing the order 1, 2 and 3 corrections as linked to there in DIPlib's source for SciPy and CuPy as well. This issue resulted in a PR to scikit-image that refactors computation of 2nd derivatives involved in the Hessian terms for the Meijering filter in scikit-image (scikit-image/scikit-image#6149).

**Comment by grlee77** [comment] 2022-05-04 13:30
In summary, this is likely not a bug in CuPy as it is mirroring SciPy's behavior. One could argue that SciPy's Gaussian filters with order > 0 should default to a floating point output type, though! That could potentially be changed over the course of a couple SciPy releases via their standard deprecation process.

**Comment by AdvancedImagingUTSW** [comment] 2022-05-04 13:52
Thank you.  I can confirm that setting the datatype as a np.float32 when it is copied to the GPU (cp.asarray) does allow me to operate the filter at larger filter sizes.  Thank you for taking the time to look into this!

**Comment by grlee77** [comment] 2022-05-04 14:14
Thanks for confirming, @AdvancedImagingUTSW. I will close this as resolved

**Closed by grlee77** 2022-05-04 14:14 UTC
Labels: bug
